### DISCUSSION TITLE
docker compose

### DISCUSSION THREAD

**Discussion by rafipiccolo** [jesec/flood#125] [General]
Hello,
I cant replace the old flood i was using with this new flood. :(
I spent arround 2Hours playing with it's dockerfile, compose, config, etc,
now it seems to work but, i cant double clic on a file to download it.

With the old flood i just added this volume and it worked
- ./rtorrent/download:/home/rtorrent/rtorrent/download
with the new one what should i do ?

This is the compose i used with the old flood

```
    rtorrent:
        image: tuxmealux/alpine-rtorrent
        container_name: rtorrent
        restart: always
        ports: 
            # rtorrent port
            - 50000:50000
            # dht
            - 6881:6881
            - 6881:6881/udp
        expose:
            # scgi / xmlrpc port
            - 16891
        volumes:
            - ./rtorrent/session:/home/rtorrent/rtorrent/.session
            - ./rtorrent/download:/home/rtorrent/rtorrent/download
            - ./rtorrent/watch:/home/rtorrent/rtorrent/watch/start

    flood:
        image: ${REGISTRY}/flood
        build: ./flood
        restart: always
        container_name: flood
        user: 666:666
        volumes:
            - ./flood:/usr/app/
            - ./rtorrent/download:/home/rtorrent/rtorrent/download
        working_dir: /usr/app
        command: node server/bin/start.js
        environment:
            - RTORRENT_SCGI_HOST=rtorrent
            - RTORRENT_SCGI_PORT=16891
        labels:
            - traefik.enable=true
            - traefik.http.routers.flood.rule=Host(`flood.${DOMAIN}`)
            - traefik.http.services.flood.loadbalancer.server.port=3000
            - traefik.http.routers.flood.tls.certresolver=le
            - traefik.http.routers.flood.entrypoints=websecure
            - traefik.http.routers.flood.middlewares=securityheaders
```

and so this is the new flood
```
    flood2:
        image: jesec/flood:master
        restart: always
        container_name: flood2
        volumes:
            # what should i use here ?
            - ./rtorrent/download:/home/rtorrent/rtorrent/download
        labels:
            - traefik.enable=true
            - traefik.http.routers.flood2.rule=Host(`flood2.${DOMAIN}`)
            - traefik.http.services.flood2.loadbalancer.server.port=3000
            - traefik.http.routers.flood2.tls.certresolver=le
            - traefik.http.routers.flood2.entrypoints=websecure
            - traefik.http.routers.flood2.middlewares=securityheaders
```
