### DISCUSSION TITLE
Strange things happen with flood and rtorrent docker

### DISCUSSION THREAD

**Discussion by lilws** [jesec/flood#255] [Q&A]
I used to get rtorrent-docker from linuxserver, but it has too many bugs so I change to romancin/rutorrent-docker. But it also has some bugs too and the dev seems to disappear atm.

Right now I change the image of rtorrent to crazy-max/docker-rtorrent-rutorrent. It took me real serious time to set it up and running with the old data. I sucessfully make it connect with flood docker too. But then I realize it is not fully compatible and act really strange. The same setup with linuxserver and romancin, it works very well. But with crazy-max it won't. 

This is my config in docker-compose:

```
rt:
  image: crazymax/rtorrent-rutorrent:latest
  container_name: rt
  volumes:
     - /volume1/docker/rt/data:/data
     - /volume1/docker/rt/passwd:/passwd
     - /volume1/docker/rt/rsock:/var/run/rtorrent
     - /volume3/tor:/downloads
     - /volume2/tor2:/downloads2
  env_file:
     - /volume1/docker/rt/rtorrent-rutorrent.env
  ports:
     - 30000:6881/udp
     - 5580:8080
     - 9000:9000
     - 8000:8000
  restart: always

floodru:
  image: jesec/flood:latest
  container_name: floodru
  user: 1026:100
  restart: always
  command: --port 3000 --rundir /config/floodjc
  volumes:
     - /volume1/docker/rt/data/:/config
     - /volume1/docker/rt/rsock:/media
     - /volume2/tor2:/downloads2
     - /volume3/tor:/downloads
  ports:
     - 3001:3000
```
Flood can stop a torrent but unable to start it. It can't add new torrent and most action will fail. When tried to move a torrent to different location, for example from /downloads/software/files.mp4 to /downloads/files.mp4, it will rename software to files.mp4 folder and store all file in there.
