### DISCUSSION TITLE
Configure tempPath directory

### DISCUSSION THREAD

**Discussion by ojio-san** [jesec/flood#268] [Ideas]
Hello,

In [config.ts](https://github.com/jesec/flood/blob/master/config.ts) we can see that `tempPath` is build by using `<rundir>/temp/` directory : this directory seems to be used for sending magnets and torrents.

Would it be possible to have a `--tempdir` or `FLOOD_OPTION_tempdir` to customize this directory ?

This way, using docker : we will be able to share this directory using volumes.

For example, with a small docker-compose.yml configuration :
```
flood:
   image: flood
[...]
   environment:
     - FLOOD_OPTION_tempdir=/mnt/tempdir
    volumes:
      - /home/user/shared-torrent-dir:/mnt/tempdir:rw
```
```
rtorrent:
   image: rtorrent
[...]
    volumes:
      - /home/user/shared-torrent-dir:/mnt/tempdir:ro
```

Thank you and have a nice day :)
