### DISCUSSION TITLE
User needs to be created after each restart

### DISCUSSION THREAD

**Discussion by the-lazy-fox** [jesec/flood#439] [Q&A]
Type: Bug Report

## Your Environment

- Version used: Docker latest
- Environment name and version:
  - Node.js version 16.10
  - npm version 7.24

## Summary

Hey there,

I have launched the docker container with the compose below. It's running and able to connect to my qbit instance.
Nevertheless, if I restart the container or down/up it again for any reasons, I need to recreate my user every single time.
The config folder is mounted correctly and permissions are the good ones.

Thanks for your help
```
 flood:
    container_name: qbittorrent-flood
    image: jesec/flood:latest
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_healthy
    network_mode: "service:vpn"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - ./config/flood:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - deunhealth.restart.on.unhealthy=true
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://172.35.0.2:3000/ || exit 1"]
      start_period: 15s
      interval: 1m30
      timeout: 10s
      retries: 3
```

## Expected Behavior

After a restart, I should be able to login instead of register

## Current Behavior

I need to register everytime

## Logs
Regarding logs, I only have this.
```
GET /api/activity-stream?historySnapshot=FIVE_MINUTE 401 14.072 ms - -
GET / 200 8.967 ms - 992
GET /static/js/main.e491eea1.js 304 1.603 ms - -
GET /static/css/main.91a3ca36ed1a96839319.css 200 23.667 ms - -
GET /api/auth/verify?1634625302041 200 8.201 ms - 75
GET /api/client/settings 401 2.939 ms - -
GET /api/settings 401 4.167 ms - -
GET /icon_maskable_180x180.png - - ms - -
GET /favicon.ico - - ms - -
GET /static/js/90.8be17c89.chunk.js 200 3.243 ms - -
GET /api/activity-stream?historySnapshot=FIVE_MINUTE 401 1.960 ms - -
Flood server 4.7.0 starting on http://0.0.0.0:3000

(node:7) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

DEP0111 comes back 90 seconds

**Comment by jesec** [comment]
The default runtime directory is `$HOME/.local/shared/flood`. You would have to use `-d` argument if you want to set it to `/config`.

**Comment by the-lazy-fox** [comment]
Hello @jesec 
I found 2 things for docker compose:
```
environment:
      HOME: /config
```
or
```
    command:
      - --rundir=/config
```
Which one do you recommend?

**Comment by jesec** [comment]
I would recommend `$HOME` since that makes things easier to manage in some cases. For instance, rTorrent exposes RPC via a socket, and it is much easier to set up when things are in the same $HOME. 

Flood also has to have direct access to qBittorrent's session directory if you want to use the "download .torrent file" function.

**Comment by the-lazy-fox** [comment]
Just to be exact, you mean like this right?
Could you please provide rtorrent + flood / qbit + flood complete docker compose files? It would be appreciated, super hard to find working confs.
```
environment:
      $HOME: /config
```

**Comment by jesec** [comment]
#120

**Comment by the-lazy-fox** [comment]
I have followed the only post related to qbit to link the rundir to /config. compose below.
My logs are still full of 
_Failed to access runtime directory_

```
  flood:
    container_name: qbittorrent-flood
    image: jesec/flood:latest
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_healthy
    network_mode: "service:vpn"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - ./config/flood:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - deunhealth.restart.on.unhealthy=true
    command: 
      - --rundir=/config
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://172.35.0.2:3000/ || exit 1"]
      start_period: 15s
      interval: 1m30
      timeout: 10s
      retries: 3
```
