### DISCUSSION TITLE
rtorrent startup takes about 16 minutes to load entries from session directory with 2.9k torrents, data stored in Samba share

### DISCUSSION THREAD

**Discussion by jonesnc** [jesec/flood#471] [Q&A] [answered]
## Question
I'm asking this question to see if my startup times are what I should expect, or if something is mis-configured.

I'm running the `jesec/flood` and `jesec/rtorrent` docker images, and I have about 2,900 torrents already added to the client. The rtorrent `/config` directory is a local directory, but the `/data` directory is a Samba share that is mounted as a Docker volume within both containers. I should also note that the `/data` directory is marked as a read-only Docker volume with `:ro` at the end of the entry.

When I initially bring up both containers and show the docker logs, this is what I see:
```bash
2021-12-21T23:46:22.682265775Z rTorrent: loading 2957 entries from session directory
2021-12-22T00:03:11.995928004Z rTorrent: started, 2957 torrents loaded
```

**As you can see, startup time took about 16 minutes. Is it expected to take this long?**

## Config

I can confirm that rtorrent is _not_ re-checking the hashes of each torrent. It's only adding the torrents from the session directory back to the client itself as part of the normal start-up procedure.

The only thing I've tried changing to try to fix this is to increase the `Maximum number of open file descriptors` from `1024` to `100,000`. That didn't seem to affect the startup time.

### `rtorrent.rc`

```
## Import default configurations
import = /etc/rtorrent/rtorrent.rc

## Listening port
network.port_range.set=6881-6881

## Run the rTorrent process as a daemon in the background
system.daemon.set = true

#network.scgi.open_port = 127.0.0.1:5000
log.xmlrpc = (cat, (cfg.logs), "xmlrpc.log")
```

### `/etc/fstab` entry
```
//Drobo5n2/Public /mnt/shares/drobo cifs uid=jonesnc,gid=jonesnc,credentials=/home/jonesnc/.smb,iocharset=utf8,vers=3.0,file_mode=0777,dir_mode=0777 0 0
```

### `docker-compose.yml` file
```yml
version: "3"
services:
  flood:
    hostname: flood
    image: jesec/flood
    user: 1000:1001
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - /home/jonesnc/rtorrent/config:/config
      - /mnt/shares/drobo/#/#downloads:/data/downloads
      - /mnt/shares/drobo:/data/drobo:ro
    ports:
      - 0.0.0.0:3001:3001

  rtorrent:
    hostname: rtorrent
    image: jesec/rtorrent
    user: 1000:1001
    restart: unless-stopped
    command: -o network.port_range.set=50000-50000,system.daemon.set=true
    environment:
      HOME: /config
    volumes:
      - /home/jonesnc/rtorrent/config:/config
      - /mnt/shares/drobo/#/#downloads:/data/downloads
      - /mnt/shares/drobo:/data/drobo:ro
    ports:
      - 0.0.0.0:50000:50000
      - 0.0.0.0:5000:5000
```

I'm running `Ubuntu Server 20.04`, `Docker version 20.10.12, build e91ed57` and `docker-compose version 1.28.5, build c4eb3a1f`. 

I can post any additional logs or config files you need, just ask.

Thanks.
