### DISCUSSION TITLE
Gluetun+Qbittorrent+Flood Docker-Compose file with traefik labels

### DISCUSSION THREAD

**Discussion by ndutg** [jesec/flood#793] [General]
Hi guys below is my successful docker-compose file for setting up Gluetun+Qbittorrent+Flood. Hope someone finds it helpful
---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    expose:
      - 6881
      - 6881/udp
      #- 8085
      #- 8989
      #- 9696
    volumes:
      - ./:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=<YOUR PRIVATE KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      - WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=Pacific/Auckland
      - SERVER_COUNTRIES=New Zealand
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
    networks:
      - proxy
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - WEBUI_PORT=8085
    volumes:
      - ./qbittorrent:/config
      - NFS:/downloads
    depends_on:
      - gluetun
    restart: always
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.qbit.entrypoints=http"
     - "traefik.http.routers.qbit.rule=Host(`qbit.mydomain.com`)"
     - "traefik.http.middlewares.qbit-https-redirect.redirectscheme.scheme=https"
     - "traefik.http.routers.qbit.middlewares=qbit-https-redirect"
     - "traefik.http.routers.qbit-secure.entrypoints=https"
     - "traefik.http.routers.qbit-secure.rule=Host(`qbit.mydomain.com`)"
     - "traefik.http.routers.qbit-secure.tls=true"
     - "traefik.http.routers.qbit-secure.service=qbit"
     - "traefik.http.services.qbit.loadbalancer.server.port=8085"
     - "traefik.docker.network=proxy"
  flood:
    container_name: flood
    image: jesec/flood
    user: 1000:1000
    restart: unless-stopped
    command: --port 3001 --allowedpath /downloads
    environment:
      HOME: /config
    volumes:
      - ./qbittorrent:/config
      - NFS:/downloads
    depends_on:
      - gluetun
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.flood.entrypoints=http"
     - "traefik.http.routers.flood.rule=Host(`flood.mydomain.com`)"
     - "traefik.http.middlewares.flood-https-redirect.redirectscheme.scheme=https"
     - "traefik.http.routers.flood.middlewares=flood-https-redirect"
     - "traefik.http.routers.flood-secure.entrypoints=https"
     - "traefik.http.routers.flood-secure.rule=Host(`flood.mydomain.com`)"
     - "traefik.http.routers.flood-secure.tls=true"
     - "traefik.http.routers.flood-secure.service=flood"
     - "traefik.http.services.flood.loadbalancer.server.port=3001"
     - "traefik.docker.network=proxy"
    networks:
      - proxy
networks:
  proxy:
    external: true
volumes:
  NFS:
    external: true

**Comment by shionryuu** [comment]
Formated Version

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    expose:
      - 6881
      - 6881/udp
      #- 8085
      #- 8989
      #- 9696
    volumes:
      - ./:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY= # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      - WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=Pacific/Auckland
      - SERVER_COUNTRIES=New Zealand
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
    networks:
      - proxy
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - WEBUI_PORT=8085
    volumes:
      - ./qbittorrent:/config
      - NFS:/downloads
    depends_on:
      - gluetun
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit.entrypoints=http"
      - "traefik.http.routers.qbit.rule=Host(qbit.mydomain.com)"
      - "traefik.http.middlewares.qbit-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.qbit.middlewares=qbit-https-redirect"
      - "traefik.http.routers.qbit-secure.entrypoints=https"
      - "traefik.http.routers.qbit-secure.rule=Host(qbit.mydomain.com)"
      - "traefik.http.routers.qbit-secure.tls=true"
      - "traefik.http.routers.qbit-secure.service=qbit"
      - "traefik.http.services.qbit.loadbalancer.server.port=8085"
      - "traefik.docker.network=proxy"
  flood:
    container_name: flood
    image: jesec/flood
    user: 1000:1000
    restart: unless-stopped
    command: --port 3001 --allowedpath /downloads
    environment:
    HOME: /config
    volumes:
      - ./qbittorrent:/config
      - NFS:/downloads
    depends_on:
      - gluetun
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flood.entrypoints=http"
      - "traefik.http.routers.flood.rule=Host(flood.mydomain.com)"
      - "traefik.http.middlewares.flood-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.flood.middlewares=flood-https-redirect"
      - "traefik.http.routers.flood-secure.entrypoints=https"
      - "traefik.http.routers.flood-secure.rule=Host(flood.mydomain.com)"
      - "traefik.http.routers.flood-secure.tls=true"
      - "traefik.http.routers.flood-secure.service=flood"
      - "traefik.http.services.flood.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
networks:
  proxy:
    external: true
volumes:
  NFS:
    external: true
```
