### ISSUE TITLE
Flood container crashes after 5 seconds

### ISSUE THREAD

**Issue by Talanor** [jesec/flood#157]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used: `jesec/flood`
- Environment name and version:
  - Docker version 19.03.13-ce, build 4484c46d9d
  - docker-compose version 1.27.4, build unknown
  - Firefox 84.0.2 (64b)
  - Chromium 87.0.4280.141
- Operating system and version:
  - Archlinux, current
- Torrent client and version: `jesec/rtorrent`

I run flood and rtorrent via this docker-compose file:

```YAML
version: '3'

services:
  rtorrent-flood:
    image: jesec/flood
    restart: unless-stopped
    depends_on:
      - rtorrent-XXXX
    volumes:
      - "./data/flood:/home/download/.local/share/flood"
      - "./data/rtorrent/XXXX/home/download:/home/download/XXXX:ro"
      - "./data/rtorrent/XXXX/home/rtorrent.sock:/tmp/socket-XXXX.sock"
    networks:
      - proxy-tier
    environment:
      VIRTUAL_HOST: "YYYYYYYYYY"
      VIRTUAL_PORT: "3000"
      LETSENCRYPT_HOST: "YYYYYYYYYY"

  rtorrent-XXXX:
    image: jesec/rtorrent
    restart: unless-stopped
    tty: true
    volumes:
      - "./data/rtorrent/XXXX/home:/home/download/.local/share/rtorrent:rw"
      - "./data/rtorrent/XXXX/rtorrent.rc:/etc/rtorrent/rtorrent.rc:ro"

networks:
  proxy-tier:
    external:
      name: proxy_proxy-tier
```

which runs behind a proxy (`jwilder/nginx-proxy:alpine` and `jrcs/letsencrypt-nginx-proxy-companion`)

Slightly modified rtorrent.rc https://pastebin.com/Z2TQCPqp

## Summary

When I load the page on firefox, I get this in the console about 5 seconds in:

![firefox-flood-error](https://user-images.githubusercontent.com/2121473/104696302-fa41c780-5705-11eb-82e2-097e99bc9b93.png)

On chromium I get:

![chromium-console-flood-error](https://user-images.githubusercontent.com/2121473/104696437-2e1ced00-5706-11eb-933d-9630e2c75705.png)

My proxy then notifies me that the flood container dies, which it does, while logging this absolute unit of a string:

https://pastebin.com/2AaLZejC

## Expected Behavior

Flood container not dying

## Current Behavior

Flood container dies

## Possible Solution

I have little clue as to what to do next since I do not see an appropriate error message. I would guess that flood crashes when the URL https://YYYY/api/activity-stream?historySnapshot=FIVE_MINUTE is accessed ? 
## Steps to Reproduce

1. `docker-compose up -d`
2. Log in
3. Wait 5 seconds
4. Profit
