### ISSUE TITLE
Transmission is not working

### ISSUE THREAD

**Issue by SSoft7** [jesec/flood#500]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release) - 4.7.0 static binary from github
- Operating system and version: Ubuntu 18.04
- Torrent client and version: Transmission: 3.00 (bb6b5a062e), RPC: 16

## Summary

Flood can no longer connect to transmission via RPC. I've tested qBittorrent 4.3.9, rTorrent 0.9.6, Deluge 2.x. All of them works except transmission.

## Expected Behavior

It should be able to connect

## Current Behavior

It can't connect

## Steps to Reproduce

1. simply add a new user and fill in all required details.

## More details
In the flood terminal logs, All I can see is the following when trying to authenticate to my flood for transmission - 

```
POST /api/auth/authenticate 401 92.396 ms - 27
POST /api/auth/authenticate 401 27.117 ms - 27
POST /api/auth/authenticate 401 0.924 ms - 27
POST /api/auth/authenticate 401 2.860 ms - 27
```

To verify if my transmission RPC endpoint is active and working, I've ran the following command
curl -u username:password https://host/path/rpc
and it was working.

I've no idea how to diagnose this issue further. Kindly provide some direction.

**Comment by Igloczek** [comment]
Same for me, `/api/client/settings` endpoint throw 500, and as a response return `Request failed with status code 404`

**Comment by Igloczek** [comment]
For a  second, I thought that I'm facing the same issue, but turns out I put wrong path as RPC URL, and it works fine now, while I have almost identical setup as yours, so probably it's not a bug in code.

You might try to restart Transmission daemon, it rejects any traffic after like 3 failed login attempts.

**Comment by SSoft7** [comment]
> For a second, I thought that I'm facing the same issue, but turns out I put wrong path as RPC URL, and it works fine now. I have almost identical setup as yours, so probably it's not a bug in code.
> 
> You might try to restart Transmission daemon, it rejects any traffic after like 3 failed auth attempts.

I've confirmed RPC URL using curl command and also I have tested on a different machine. So fail authentication is not happening on my case. Are you using the release version or source build ?

**Comment by Igloczek** [comment]
I build from source, on Node v16.

**Comment by realivanjx** [comment]
when i access transmission on my phone with flood ui the authentication fails silenty later on and i got the message to restart the transmission because of many failed login attempts. clearing the cookie brings back the login prompt but then it repeats again after a while. this never happens with the default gui though.

**Comment by jesec** [comment]
`/api/auth/authenticate` does not involve Transmission.

It is authentication into Flood. Flood has its own user accounts and authentication. Did you type the wrong password?

**Comment by realivanjx** [comment]
try to delete the sw.js file. it is messing up with the auth on my chrome android. works fine now.

**Comment by joyarzun** [comment]
Using a fresh Transmission installation doesn't work for me

My current setup:

- AWS EC2 Instance t4g.small (ARM)
- Ubuntu 22.04.2 LTS
- Docker  24.0.2, build cb74dfc
-  Flood server 4.7.0
- Transmission 4.0.3

docker-compose:

```yaml
---
version: "3"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:arm64v8-latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - USER=redacted
      - PASS=redacted
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  flood:
    hostname: flood
    image: jesec/flood
    user: 1000:1001
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - ./floodconfig:/config
      - ./downloads:/data
    ports:
      - 3001:3001
```

I've tried with `http://localhost:9091/transmission/rpc` and `http://transmission:9091/transmission/rpc`

Adding a torrent file the api fails with:

![image](https://github.com/jesec/flood/assets/828211/bdaa98b6-119b-422b-85df-a9eacd5513ca)

Any advise?
