### ISSUE TITLE
Include Docker Compose In Documentation

### ISSUE THREAD

**Issue by spencerthayer** [jesec/flood#638]
It's clear that Flood can be ran in docker using a compose file given the discussion in issue #120 so why hasn't this been officially documented?

```
services:
  flood:
    hostname: flood
    image: docker.io/jesec/flood
    user: 1000:1001
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - /home/jc/dlconfig:/config
      - /mnt/data0:/data
    ports:
      - 127.0.0.1:3001:3001
```
