### ISSUE TITLE
flood with qbittorrent : No such method TorrentsController

### ISSUE THREAD

**Issue by Kosteron** [jesec/flood#820]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version : Flood server 4.8.4
  - Commit ID : none
- Environment name and version:
  - Node.js version `the one from the flood docker`
  - npm version `the one from the flood docker`
  - Web browser : Firefox 128.3.1esr (64 bits)
- Operating system and version: Linux
- Torrent client and version: QBITTORRENT_VERSION=5.0.1-r0 as mentioned [here](https://hub.docker.com/layers/linuxserver/qbittorrent/latest/images/sha256-25127db73150b3de5134e35849ac436136cdf711b6b1750e35cf1060d2d27168?context=explore)

## Summary

Hi, I'm trying to create a docker-compose stack with flood as front-end for qbittorrent, but I have some trouble with it.
Once everything is started, I can add a torrent, but when I want to stop or resume it, I got this error

``` bash
...
qbittorrent          | QMetaObject::invokeMethod: No such method TorrentsController::pauseAction()
flood                | POST /api/torrents/stop 500 17.917 ms - 74
qbittorrent          | QMetaObject::invokeMethod: No such method TorrentsController::pauseAction()
flood                | POST /api/torrents/stop 500 11.144 ms - 74
qbittorrent          | QMetaObject::invokeMethod: No such method TorrentsController::resumeAction()
flood                | POST /api/torrents/start 500 15.480 ms - 74
...
```

Also the flood UI blink and show shortly the "unable to connect to qbittorrent" UI and go back to the main page

## Expected Behavior

The torrent should be stopped or started accordingly

## Current Behavior

Unable to start or stop torrent

## Possible Solution

Maybe update the method call by flood for latest qbittorrent version ?

## Steps to Reproduce

1. Start a docker-compose stack with jesec/flood latest version and lscr.io/linuxserver/qbittorrent latest version
2. Add a torrent on flood and stop it
3. See the error 500 message on the output of docker compose log

Here is a sample docker-compose file to reproduce the problem :

``` yaml
services:
  flood:
    hostname: flood
    container_name: flood
    image: jesec/flood
    user: 1001:1001
    restart: unless-stopped
    command: --port 3001
    ports:
      - 3001:3001
    environment:
      - PUID=1001
      - PGID=1001
      - HOME=/config
    volumes:
      - qbittorrent-config:/config
      - /home/service/qbittorrent/download:/downloads

  qbittorrent:
    hostname: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - /home/service/qbittorrent/download:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

volumes:
  qbittorrent-config:
```

## Context

Trying to stop or resume a torrent
