### ISSUE TITLE
Clarification Needed: Directory Mapping with Dockerized Torrent Client and EACCES Error

### ISSUE THREAD

**Issue by wgomg** [jesec/flood#873]
Type: Documentation Issue

### Description of the Issue

I'm running Flood on the host machine and connecting it to an rTorrent instance running inside a Docker container. Everything works well for existing torrents, but when I try to add a new torrent through the Flood web UI (or move an existing torrent), Flood fails with an `EACCES: permission denied, mkdir '/home/<user>'` error. The `<user>` part refers to the user *inside* the Docker container, and Flood is trying to create this directory on the *host* filesystem, which is not only incorrect but also impossible.

It seems Flood is attempting to directly create directories based on internal Docker paths, which is inappropriate for this setup. I'm wondering if there's a way to configure or disable this behavior.

### Environment

*   **Flood version:** 4.9.3
*   **rTorrent version:** Rakshasa's BitTorrent client version 0.9.8
*   **Operating System (Flood host):** Debian 12
*   **Docker Image (rTorrent):** Custom (based on Alpine, see Dockerfile below)
*   **Node.js version:** v18.19.0
*   **npm version:** 9.2.0

### Relevant Configuration

*   **Docker Compose file:**

    ```yaml
    services:
      <service>:
        build: .
        container_name: <container_name>
        volumes:
          - /mnt:/home/<user>/data
          - /home/<user>/.config/<container_name>:/home/<user>/config
        ports:
          - '<port>:<port>/tcp'
          - '<port>:<port>/udp'
        restart: unless-stopped
        networks:
          net:
            ipv4_address: 172.18.0.2

    networks:
      net:
        ipam:
          config:
            - subnet: 172.18.0.0/16
    ```

*   **Flood Launch Command (on the host):**

    ```bash
    flood --host=0.0.0.0 --port=3000 --rtsocket=/home/<user>/.config/<container_name>/rtorrent/session/rpc.socket --rundir=/home/<user>/.config/<container_name>/flood --auth=default
    ```

### Question & Request for Clarification

1.  Is there a configuration option in Flood to properly handle directory mapping when working with a Dockerized torrent client?

2.  More specifically, is there a way to **completely disable Flood's attempt to create directories** directly? This seems unnecessary in my setup, as I only need Flood to interact with rTorrent (which handles the file management) and it's causing errors. It feels like Flood shouldn't assume write access on the host filesystem in this scenario.

3.  If disabling directory creation isn't possible, could you provide guidance on how to configure Flood to correctly interpret the directory structure *inside* the Docker container while running on the host?

I want to emphasize that Flood *does* successfully read data from rTorrent and displays the status of existing torrents, so the connection is established. The problem only arises when *adding* or *moving* torrents, at which point Flood tries to create a directory using the Docker container's internal path, causing the `EACCES` error.

Any help or clarification on this issue would be greatly appreciated. Thank you!

**Comment by trim21** [comment]
I would suggest you run both flood and rtorrent in container, or run non of them in container.

If (like what you are currently doing) you run rtorrent in container and run flood in the host, you will have to mount the path as-is  or use soft link to make flood fully functional, becuase currently there is no way to configure Flood to correctly interpret the directory structure.

**Comment by trim21** [comment]
> I want to emphasize that Flood does successfully read data from rTorrent and displays the status of existing torrents, so the connection is established. The problem only arises when adding or moving torrents, at which point Flood tries to create a directory using the Docker container's internal path, causing the EACCES error.

flood may try to get data in 2 ways. for example, the status of existing torrents is reading from rpc, which doesn't involve file path. but when it try to move files, create new download, or download torrent files, it will need do some file io, and you encounter an problem here.

**Comment by wgomg** [comment]
> you will have to mount the path of rtorrent as-is

I'm sorry, i don't fully understand what do you mean by this.

>or use some kind of soft/hard link to manually mapping the path to make flood fully functional

They only way i see this posible is creating a soft link on the host like `/home/<container_user>`, but that seems wrong in so many ways. 

I think the real issue is flood forcibly trying to create directories but it seems there is no way to disable this behavior, am i correct?

**Comment by trim21** [comment]
> > you will have to mount the path of rtorrent as-is
> 
> I'm sorry, i don't fully understand what do you mean by this.


I suggest you do this, so flool and rtorrent will see same directory structure:

```yaml
services:
  <service>:
    build: .
    container_name: <container_name>
    volumes:
      - /mnt:/mnt
      - /home/<user>/data:/home/<user>/data
      - /home/<user>/.config/<container_name>:/home/<user>/.config/<container_name>
      - /home/<user>/config:/home/<user>/config
```

> > or use some kind of soft/hard link to manually mapping the path to make flood fully functional
> 
> They only way i see this posible is creating a soft link on the host like `/home/<container_user>`, but that seems wrong in so many ways.
> 
> I think the real issue is flood forcibly trying to create directories but it seems there is no way to disable this behavior, am i correct?

Not really, for example, what will happen when you use `remove torrent data` function of flood?
